In [1]:
#full data extraction  from  a realistic sales data 

import pandas as pd
import numpy as np
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import random


#simulate 60 days of sales data
customers = ["Amazon", "Walmart", "Target", "BestBuy", "Costco", "eBay"]
data = []

#for loop to generate data
start_date = datetime.date(2025, 4, 1)
for i in range(61):  # 0 to 60 (61 days)
    date = start_date + datetime.timedelta(days=i)
    for _ in range(random.randint(3, 6)):  # 3 to 6 transactions per day
        data.append({
            "id": random.randint(1000, 9999),
            "customers": random.choice(customers),
            "date": date.isoformat(),
            "amount": random.randint(100, 2000),
            "last_updated": (
                datetime.datetime.combine(date, datetime.time()) +
                datetime.timedelta(
                    hours=random.randint(0, 23),
                    minutes=random.randint(0, 59),
                    seconds=random.randint(0, 59)
                )
            ).isoformat()
        })

df = pd.DataFrame(data)
df.to_csv("sales_data.csv", index=False)
df.head()



#full data extraction  from  a realistic sales data
df_full=pd.read_csv("sales_data.csv", parse_dates=['date','last_updated'])
print("Full Data Extracted:")
df_full.head()

#incremental data extraction
#simulate last extraction date
last_extraction_date = datetime.datetime(2025, 4, 15, 12, 0, 0)
df_incremental = df_full[df_full['last_updated'] > last_extraction_date]
print(f"\nIncremental Data Extracted (after {last_extraction_date}):")
df_incremental.head()

Full Data Extracted:

Incremental Data Extracted (after 2025-04-15 12:00:00):

      id customers       date  amount        last_updated
61  8383   BestBuy 2025-04-15    1736 2025-04-15 19:16:05
65  6762    Target 2025-04-15    1712 2025-04-15 22:55:35
66  7452    Target 2025-04-16     532 2025-04-16 03:19:24
67  9059    Target 2025-04-16    1282 2025-04-16 13:54:47
68  3591   BestBuy 2025-04-16    1496 2025-04-16 19:57:38